# Generated by Django 2.1 on 2018-09-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imginfo',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
