# Generated by Django 2.1 on 2018-11-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_imginfo_is_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageUrl', models.FileField(upload_to='')),
                ('ProjectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='ourprojectimages',
            name='ourProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.OurProjects'),
        ),
    ]
