# Generated by Django 2.1 on 2018-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20181104_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojectimages',
            name='ProjectName',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='about',
            field=models.CharField(max_length=600),
        ),
    ]
